<a href="https://colab.research.google.com/github/ShubhamSingh120/RL-Repository/blob/main/Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
R = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100]])

In [ ]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [4]:
Q = np.matrix(np.zeros([6,6]))

In [5]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [16]:
gamma = 0.8
initial_state = 1

In [17]:
def available_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row>=0)[1]
  return av_act

In [18]:
available_act = available_actions(initial_state)

In [19]:
available_act

array([3, 5])

In [20]:
def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_act, 1))
  return next_action

In [28]:
action = sample_next_action(available_act)

In [29]:
action

5

In [30]:
def update(current_state, action, gamma):
  max_index = np.where(Q[action,]==np.max(Q[action,]))[1]

  if max_index.shape[0]>1:
    max_index = int(np.random.choice(max_index, size=1))
  else:
    max_index = int(max_index)
  max_value = Q[action, max_index]

  #Q_Learning Formula
  Q[current_state, action] = R[current_state, action] + gamma*max_value

#Update Q matrix
update(initial_state, action, gamma)

In [31]:
Q

matrix([[  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.]])

In [40]:
initial_state = 4

In [41]:
action = sample_next_action(available_act)

In [42]:
action

5

In [44]:
update(initial_state, action, gamma)

In [45]:
Q

matrix([[  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.]])